/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Metadata associated with a photo stack.
 *
 * Combines EXIF tags (from image files), XMP tags (embedded or sidecar),
 * and custom tags (from the sidecar database) into a unified view.
 */
export interface JsMetadata {
  /** Standard EXIF tags from the image file (Make, Model, DateTime, etc.) */
  exifTags: Record<string, string>
  /** XMP/Dublin Core metadata tags */
  xmpTags: Record<string, string>
  /** Custom application metadata stored in the sidecar database */
  customTags: Record<string, any>
}
/**
 * A unified representation of a single scanned photo from an Epson FastFoto scanner.
 *
 * Groups the original scan, enhanced version, and back-of-photo image into
 * a single logical unit with associated metadata.
 */
export interface JsPhotoStack {
  /** Unique identifier derived from the base filename */
  id: string
  /** Path to the original front scan (may be null) */
  original?: string
  /** Path to the enhanced/color-corrected scan (may be null) */
  enhanced?: string
  /** Path to the back-of-photo scan (may be null) */
  back?: string
  /** Combined metadata from all sources */
  metadata: JsMetadata
}
/** A key-value pair for search filters. */
export interface JsKeyValue {
  /** The tag name to filter on */
  key: string
  /** The value substring to search for */
  value: string
}
/**
 * Query parameters for searching photo stacks.
 *
 * All filters use AND logic - a stack must match all specified criteria.
 */
export interface JsSearchQuery {
  /** Free-text search across ID and all metadata */
  text?: string
  /** EXIF tag filters (all must match) */
  exifFilters?: Array<JsKeyValue>
  /** Custom tag filters (all must match) */
  customFilters?: Array<JsKeyValue>
  /** Filter by presence of back scan */
  hasBack?: boolean
  /** Filter by presence of enhanced scan */
  hasEnhanced?: boolean
}
/** A paginated result containing a page of photo stacks and pagination metadata. */
export interface JsPaginatedResult {
  /** The photo stacks in this page. */
  items: Array<JsPhotoStack>
  /** Total number of stacks across all pages. */
  totalCount: number
  /** The offset used for this page. */
  offset: number
  /** The page size limit used for this page. */
  limit: number
  /** Whether there are more items beyond this page. */
  hasMore: boolean
}
/** Options for creating a PhotostaxRepository. */
export interface RepositoryOptions {
  /**
   * Whether to recurse into subdirectories (default: false).
   *
   * Set to `true` when the photo library uses FastFoto's folder-based
   * organisation (e.g. `1984_Mexico/`, `SteveJones/`).
   */
  recursive?: boolean
}
/**
 * A repository for accessing Epson FastFoto photo stacks from a local directory.
 *
 * Provides methods to scan, retrieve, and modify photo stacks and their metadata.
 */
export declare class PhotostaxRepository {
  /**
   * Create a new repository rooted at the given directory path.
   *
   * @param directoryPath - Path to the directory containing FastFoto photo files
   * @param options - Optional configuration (e.g. `{ recursive: true }`)
   * @throws Error if the path is invalid
   */
  constructor(directoryPath: string, options?: RepositoryOptions | undefined | null)
  /**
   * Scan the repository and return all discovered photo stacks (fast, no file-based metadata).
   *
   * Returns stacks with paths and folder-derived metadata only.
   * Use `scanWithMetadata()` to load EXIF/XMP/sidecar data for all stacks,
   * or `loadMetadata(stackId)` to load metadata for individual stacks on demand.
   *
   * @returns Array of photo stacks found in the repository
   * @throws Error if the directory cannot be accessed
   */
  scan(): Array<JsPhotoStack>
  /**
   * Scan the repository and return all photo stacks with full metadata loaded.
   *
   * This is the slower path that reads EXIF, XMP, and sidecar data for every stack.
   * Prefer `scan()` + `loadMetadata()` for lazy-loading in large repositories.
   *
   * @returns Array of photo stacks with complete metadata
   * @throws Error if the directory cannot be accessed
   */
  scanWithMetadata(): Array<JsPhotoStack>
  /**
   * Retrieve a single photo stack by its ID.
   *
   * @param id - The stack identifier (base filename without suffix)
   * @returns The photo stack with the given ID
   * @throws Error if the stack is not found or cannot be accessed
   */
  getStack(id: string): JsPhotoStack
  /**
   * Load full metadata (EXIF, XMP, sidecar) for a specific stack.
   *
   * Use with `scan()` for lazy-loading: scan first to get lightweight stacks,
   * then load metadata on demand for individual stacks.
   *
   * @param stackId - The stack identifier
   * @returns The loaded metadata
   * @throws Error if the stack is not found or metadata cannot be read
   */
  loadMetadata(stackId: string): JsMetadata
  /**
   * Read the raw bytes of an image file.
   *
   * @param path - Path to the image file (from a PhotoStack)
   * @returns Buffer containing the image bytes
   * @throws Error if the file cannot be read
   */
  readImage(path: string): Buffer
  /**
   * Write metadata tags to a photo stack.
   *
   * XMP tags are written to the image file (or sidecar for TIFF).
   * Custom and EXIF tags are stored in the sidecar database.
   *
   * @param stackId - The ID of the stack to update
   * @param metadata - The metadata to write
   * @throws Error if the stack is not found or metadata cannot be written
   */
  writeMetadata(stackId: string, metadata: JsMetadata): void
  /**
   * Search for photo stacks matching the given query.
   *
   * @param query - Search criteria (all filters are AND'd together)
   * @returns Array of matching photo stacks
   * @throws Error if the repository cannot be scanned
   */
  search(query: JsSearchQuery): Array<JsPhotoStack>
  /**
   * Scan the repository and return a paginated result of photo stacks.
   *
   * @param offset - Number of stacks to skip (0-based)
   * @param limit - Maximum number of stacks to return
   * @param loadMetadata - When true, loads EXIF/XMP/sidecar metadata for each stack in the page
   * @returns Paginated result with items and pagination metadata
   * @throws Error if the directory cannot be accessed
   */
  scanPaginated(offset: number, limit: number, loadMetadata?: boolean | undefined | null): JsPaginatedResult
  /**
   * Search for photo stacks and return a paginated result.
   *
   * @param query - Search criteria (all filters are AND'd together)
   * @param offset - Number of matching stacks to skip (0-based)
   * @param limit - Maximum number of matching stacks to return
   * @returns Paginated result with items and pagination metadata
   * @throws Error if the repository cannot be scanned
   */
  searchPaginated(query: JsSearchQuery, offset: number, limit: number): JsPaginatedResult
}
